version: '3.3'
services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - ws_proxy
    command: redis-server --port 6379
    ports:
      - 6379:6379
  was:
    container_name: cba_was
    networks:
      - ws_proxy
    build:
      context: .
      dockerfile: ./dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
networks:
  ws_proxy:
    external: true
